### ISSUE TITLE
App Crash after tap on resend code button

### ISSUE THREAD

**Issue by NayanGaikwad** [MSG91/sendotp-ios#3]
2018-07-25 01:26:12.386397+0530 GpsUI[8174:231045] Request reply: 
{"type":"error"}
2018-07-25 01:26:12.386797+0530 GpsUI[8174:231045] {
    type = error;
}
=================================================================
Main Thread Checker: UI API called on a background thread: -[UIAlertView initWithTitle:message:delegate:cancelButtonTitle:otherButtonTitles:]
PID: 8174, TID: 231045, Thread name: (none), Queue name: NSOperationQueue 0x604000031260 (QOS: UNSPECIFIED), QoS: 0
Backtrace:
4   SendOTPFramework                    0x000000010e48cf58 __55-[AuthenticationViewController resendCodeButtonAction:]_block_invoke + 770
5   CFNetwork                           0x00000001138b6ae8 __75-[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]_block_invoke + 19
6   CFNetwork                           0x00000001138b6341 __49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke + 147
7   Foundation                          0x000000010e4ed22f __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
8   Foundation                          0x000000010e4ed091 -[NSBlockOperation main] + 68
9   Foundation                          0x000000010e4eb54e -[__NSOperationInternal _start:] + 778
10  libdispatch.dylib                   0x000000011456133d _dispatch_client_callout + 8
11  libdispatch.dylib                   0x00000001145669f3 _dispatch_block_invoke_direct + 592
12  libdispatch.dylib                   0x000000011456133d _dispatch_client_callout + 8
13  libdispatch.dylib                   0x00000001145669f3 _dispatch_block_invoke_direct + 592
14  libdispatch.dylib                   0x0000000114566783 dispatch_block_perform + 109
15  Foundation                          0x000000010e4e755c __NSOQSchedule_f + 342
16  libdispatch.dylib                   0x000000011456133d _dispatch_client_callout + 8
17  libdispatch.dylib                   0x0000000114567754 _dispatch_continuation_pop + 967
18  libdispatch.dylib                   0x0000000114565b85 _dispatch_async_redirect_invoke + 780
19  libdispatch.dylib                   0x000000011456d102 _dispatch_root_queue_drain + 772
20  libdispatch.dylib                   0x000000011456cda0 _dispatch_worker_thread3 + 132
21  libsystem_pthread.dylib             0x0000000114a2d169 _pthread_wqthread + 1387
22  libsystem_pthread.dylib             0x0000000114a2cbe9 start_wqthread + 13
2018-07-25 01:26:12.389579+0530 GpsUI[8174:231045] [reports] Main Thread Checker: UI API called on a background thread: -[UIAlertView initWithTitle:message:delegate:cancelButtonTitle:otherButtonTitles:]
PID: 8174, TID: 231045, Thread name: (none), Queue name: NSOperationQueue 0x604000031260 (QOS: UNSPECIFIED), QoS: 0
Backtrace:
4   SendOTPFramework                    0x000000010e48cf58 __55-[AuthenticationViewController resendCodeButtonAction:]_block_invoke + 770
5   CFNetwork                           0x00000001138b6ae8 __75-[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]_block_invoke + 19
6   CFNetwork                           0x00000001138b6341 __49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke + 147
7   Foundation                          0x000000010e4ed22f __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
8   Foundation                          0x000000010e4ed091 -[NSBlockOperation main] + 68
9   Foundation                          0x000000010e4eb54e -[__NSOperationInternal _start:] + 778
10  libdispatch.dylib                   0x000000011456133d _dispatch_client_callout + 8
11  libdispatch.dylib                   0x00000001145669f3 _dispatch_block_invoke_direct + 592
12  libdispatch.dylib                   0x000000011456133d _dispatch_client_callout + 8
13  libdispatch.dylib                   0x00000001145669f3 _dispatch_block_invoke_direct + 592
14  libdispatch.dylib                   0x0000000114566783 dispatch_block_perform + 109
15  Foundation                          0x000000010e4e755c __NSOQSchedule_f + 342
16  libdispatch.dylib                   0x000000011456133d _dispatch_client_callout + 8
17  libdispatch.dylib                   0x0000000114567754 _dispatch_continuation_pop + 967
18  libdispatch.dylib                   0x0000000114565b85 _dispatch_async_redirect_invoke + 780
19  libdispatch.dylib                   0x000000011456d102 _dispatch_root_queue_drain + 772
20  libdispatch.dylib                   0x000000011456cda0 _dispatch_worker_thread3 + 132
21  libsystem_pthread.dylib             0x0000000114a2d169 _pthread_wqthread + 1387
22  libsystem_pthread.dylib             0x0000000114a2cbe9 start_wqthread + 13
2018-07-25 01:26:12.440559+0530 GpsUI[8174:231045] *** Assertion failure in -[UIKeyboardTaskQueue waitUntilAllTasksAreFinished], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3698.31/Keyboard/UIKeyboardTaskQueue.m:433
2018-07-25 01:26:12.447056+0530 GpsUI[8174:231045] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '-[UIKeyboardTaskQueue waitUntilAllTasksAreFinished] may only be called from the main thread.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000011267012b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010ead9f41 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001126752f2 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000010e57ad69 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   UIKit                               0x000000011065449d -[UIKeyboardTaskQueue waitUntilAllTasksAreFinished] + 380
	5   UIKit                               0x000000010fbc499e -[UIKeyboardImpl setDelegate:force:] + 1596
	6   UIKit                               0x00000001100b3027 -[UIPeripheralHost(UIKitInternal) _reloadInputViewsForResponder:] + 1271
	7   UIKit                               0x000000010f94994f -[UIWindow _makeKeyWindowIgnoringOldKeyWindow:] + 1002
	8   UIKit                               0x00000001105c3e41 -[_UIAlertControllerShimPresenterWindow presentAlertController:animated:completionBlock:] + 361
	9   UIKit                               0x00000001105c25ea -[_UIAlertControllerShimPresenter _presentAlertControllerAnimated:completion:] + 216
	10  UIKit                               0x000000010fcb1757 -[UIAlertView _showAnimated:] + 293
	11  SendOTPFramework                    0x000000010e48cf6c __55-[AuthenticationViewController resendCodeButtonAction:]_block_invoke + 790
	12  CFNetwork                           0x00000001138b6ae8 __75-[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]_block_invoke + 19
	13  CFNetwork                           0x00000001138b6341 __49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke + 147
	14  Foundation                          0x000000010e4ed22f __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	15  Foundation                          0x000000010e4ed091 -[NSBlockOperation main] + 68
	16  Foundation                          0x000000010e4eb54e -[__NSOperationInternal _start:] + 778
	17  libdispatch.dylib                   0x000000011456133d _dispatch_client_callout + 8
	18  libdispatch.dylib                   0x00000001145669f3 _dispatch_block_invoke_direct + 592
	19  libdispatch.dylib                   0x000000011456133d _dispatch_client_callout + 8
	20  libdispatch.dylib                   0x00000001145669f3 _dispatch_block_invoke_direct + 592
	21  libdispatch.dylib                   0x0000000114566783 dispatch_block_perform + 109
	22  Foundation                          0x000000010e4e755c __NSOQSchedule_f + 342
	23  libdispatch.dylib                   0x000000011456133d _dispatch_client_callout + 8
	24  libdispatch.dylib                   0x0000000114567754 _dispatch_continuation_pop + 967
	25  libdispatch.dylib                   0x0000000114565b85 _dispatch_async_redirect_invoke + 780
	26  libdispatch.dylib                   0x000000011456d102 _dispatch_root_queue_drain + 772
	27  libdispatch.dylib                   0x000000011456cda0 _dispatch_worker_thread3 + 132
	28  libsystem_pthread.dylib             0x0000000114a2d169 _pthread_wqthread + 1387
	29  libsystem_pthread.dylib             0x0000000114a2cbe9 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by coderShiv** [comment]
@NayanGaikwad Hi, have you implement this SDK with your own view controller? If yes then, Please explain what changes have you made.
Thanks in advance.

**Comment by hussain3152** [comment]
This issue is fixed in the latest update
